# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('item', models.TextField()),
                ('price', models.TextField()),
                ('stock', models.BooleanField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('url', models.TextField()),
                ('embed', models.TextField()),
                ('release_number', models.TextField()),
                ('release_medium', models.TextField()),
                ('release_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('embed', models.TextField()),
            ],
        ),
    ]
