# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='release',
            old_name='release_medium',
            new_name='medium'
        )
    ]
